In [5]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [6]:
# Read NPZ file from data
data_cli = np.load('/home/raykp/sp26/ml/explode/data/cyl/id00002/cx241203_id00002_pvi_idx00000.npz')
data_pli = np.load('/home/raykp/sp26/ml/explode/data/pli/id00001/pli240420_id00001_pvi_idx00000.npz')

In [9]:
pd.DataFrame(data_pli)

                            0
0                    sim_time
1                  av_density
2                 av_pressure
3              av_temperature
4                density_case
5             density_cushion
6          density_maincharge
7         density_outside_air
8             density_striker
9               density_throw
10                energy_case
11             energy_cushion
12          energy_maincharge
13         energy_outside_air
14             energy_striker
15               energy_throw
16         Fraction_vofm_case
17      Fraction_vofm_cushion
18   Fraction_vofm_maincharge
19  Fraction_vofm_outside_air
20      Fraction_vofm_striker
21        Fraction_vofm_throw
22         Fraction_vofm_Void
23           plst_strain_case
24        plst_strain_striker
25          plst_strain_throw
26              pressure_case
27           pressure_cushion
28        pressure_maincharge
29       pressure_outside_air
30           pressure_striker
31             pressure_throw
32           sound_speed_case
33        sound_speed_cushion
34     sound_speed_maincharge
35    sound_speed_outside_air
36        sound_speed_striker
37          sound_speed_throw
38           strain_rate_case
39        strain_rate_striker
40          strain_rate_throw
41           temperature_case
42          temperature_throw
43                  Uvelocity
44                  vofm_case
45               vofm_cushion
46            vofm_maincharge
47           vofm_outside_air
48               vofm_striker
49                 vofm_throw
50                  vofm_Void
51                  Wvelocity
52                     Rcoord
53                     Zcoord

In [8]:
pd.DataFrame(data_cli)

                       0
0               sim_time
1             av_density
2            av_pressure
3         av_temperature
4      burn_frac_booster
5   burn_frac_maincharge
6        density_booster
7     density_maincharge
8         energy_booster
9      energy_maincharge
10      pressure_booster
11   pressure_maincharge
12             Uvelocity
13          vofm_booster
14       vofm_maincharge
15             vofm_Void
16             vofm_wall
17             Wvelocity
18                Rcoord
19                Zcoord